version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: /
    groups:
      major:
        update-types:
          - "major"
        patterns:
          - "*"
      minor:
        update-types:
          - "minor"
        patterns:
          - "*"
      patch:
        update-types:
          - "patch"
        patterns:
          - "*"
    schedule:
      interval: 'weekly'
    registries:
      - jfrog-artifactroy


registries:
  jfrog-artifactroy:
    type: "rubygems-server"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/gems/dependabot_first_responder/"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.JFROG_ARTIFACTORY_TOKEN }}"
