version: 2
updates:
  - package-ecosystem: 'bundler'
    directories:
      - '**/*'
    groups:
      # Dependabot requires separate groups for version and security updates
      # By default, dependabot only updates packages explicitly defined in Gemfile
      bundler-nonbreaking-proximal-dependency-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    schedule:
      interval: 'weekly'
    registries:
      - jfrog-artifactroy


registries:
  jfrog-artifactroy:
    type: "rubygems-server"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/gems/dependabot_first_responder"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.JFROG_ARTIFACTORY_TOKEN }}"
    replaces-base: true
