version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: /
    schedule:
      interval: 'weekly'
    registries:
      - jfrog-artifactroy


registries:
  jfrog-artifactroy:
    type: "rubygems-server"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/gems/dependabot_first_responder/"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.JFROG_ARTIFACTORY_TOKEN }}"
